export const INCREMENT_CHUTZPAH = 'INCREMENT_CHUTZPAH';
export type INCREMENT_CHUTZPAH = typeof INCREMENT_CHUTZPAH;


export const DECREMENT_CHUTZPAH = 'DECREMENT_CHUTZPAH';
export type DECREMENT_CHUTZPAH = typeof DECREMENT_CHUTZPAH;